# Setup
title:               Pioneergu
tagline:             'a Blog'
description:         'Try everything and try everyday'
url:                 https://pioneergu.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pioneergu
  avatar:            ./public/images/moon-round.png
  description:       
  url:               https://pioneergu.github.io
  email:             hangmoonam@gmail.com


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
