# Setup
title:               Pioneergu
tagline:             'a Blog'
description:         'Try everything and try everyday'
url:                 https://pioneergu.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pioneergu
  avatar:            ./public/images/moon-round.png
  description:       
  url:               https://pioneergu.github.io
  email:             hangmoonam@gmail.com

# defaults:
#   - 
#     permalink: /posts/:title/

# jekyll-archives:
#   enabled: [categories, tags]
#   layouts:
#     category: category
#     tag: tag
#   permalinks:
#     tag: /tags/:name/
#     category: /categories/:name/

collections:
  category:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Gems
plugins:      # << Plugin에 적힌 Gem이 Github Pages에서 작동함. Gemspec은 Bundler에서 
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
